name: Setup
description: Setup environment for building and deploying the project
runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    # Restore pnpm cache only (pnpm manages Node.js version independently)
    - name: Restore pnpm cache
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        cache: pnpm

    - name: Install dependencies
      run: pnpm install
      shell: bash
